Repository E-GaeMuYac/BE, pull requests merged in 2023-02, with the labels that each got.

#209 #204 🚑 fix : Rate Limit 미들웨어 딜레이 추가
  src/architecture/services/users.service.js
  src/middlewares/rateLimit.middleware.js
  src/routes/users.route.js
Labels: bug, backend

#217 #216/auth
  src/app.js
  src/architecture/services/allergies.service.js
  src/architecture/services/products.service.js
  src/middlewares/authUser.middleware.js
Labels: backend

#229 ✨ #228 FEAT: 영문 검색 기능 추가
  README.md
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/migrations/202301020726298-create-medicines.js
  src/models/medicines.js
Labels: backend, feature

#230 ✨ #228 FEAT: 영문 검색 기능 추가
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/migrations/202301020726298-create-medicines.js
  src/models/medicines.js
Labels: backend

#232 🐛 #231 FIX: 도움 돼요, 도움 안돼요 버튼 수정
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: bug, backend

#235 ✨ #207 FEAT: 신고하기 버튼 및 조회 시 신고 배열 보내주기 구현
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/migrations/20230112072643-create-reivews.js
  src/models/reviews.js
  src/routes/reviews.route.js
Labels: backend, feature

#234 :bug: #233 FIX: 약 type 검색 안되는 문제 해결
  src/architecture/controllers/reviews.controller.js
  src/architecture/services/products.service.js
Labels: bug, backend

#236 Dev
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/products.service.js
  src/architecture/services/reviews.service.js
  src/migrations/20230112072643-create-reivews.js
  src/models/reviews.js
  src/routes/reviews.route.js
Labels: bug, backend, feature

#240 #239 🔥 fix : 이메일 인증 삭제
  src/architecture/controllers/users.controller.js
  src/architecture/services/users.service.js
  src/routes/users.route.js
Labels: backend

#238 :bug: #237 FIX: 리뷰 페이지네이션 버그 수정
  src/architecture/repositories/reviews.repository.js
Labels: bug, backend

#243 🐛 #242 FIX: 마이페이지 리뷰 조회 수정
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: bug, backend

#244 🐛 #242 FIX: 마이페이지 리뷰 조회 수정
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: bug, backend

#246 :bug: #245 FIX: 리뷰 좋아요순 정렬 수정
  src/architecture/repositories/reviews.repository.js
Labels: bug, backend

#252 #251 🐛 fix : 마이리뷰조회 페이지네이션 수정
  src/architecture/repositories/reviews.repository.js
Labels: bug, backend

#260 #213 🔒 fix : Cors Origin 수정
  src/app.js
Labels: bug, backend

#271 Dev
  README.md
  src/architecture/services/reviews.service.js
Labels: bug, documentation, backend

#259 :sparkles: #257 FEAT: swagger-autogen 기능 적용
  package-lock.json
  package.json
  src/app.js
  src/swagger-output.json
  src/swagger.js
Labels: enhancement, backend, feature

#277 🎨 #257 FIX : swagger 파일 위치 변경
  README.md
  package-lock.json
  src/app.js
  src/swagger.js
  swagger-output.json
  swagger.js
Labels: backend

#280 #279 🐛 fix : swagger 스키마 수정
  swagger-output.json
Labels: bug, backend

#282 :bulb: FIX: 불필요한 주석 삭제
  src/app.js
  src/architecture/controllers/login.controller.js
  src/architecture/repositories/login.repository.js
  src/architecture/services/login.service.js
Labels: backend

#283 #279 🐛 fix : swagger 수정
  swagger-output.json
Labels: bug, backend

#285 :art: FIX : 알러지 등록/삭제 description 추가
  swagger-output.json
Labels: backend
