Repository E-GaeMuYac/BE, pull requests merged in 2023-01, with the labels that each got.

#19 일반 로그인 기능 구현
  .vscode/settings.json
  package-lock.json
  package.json
  src/app.js
  src/architecture/controllers/login.controller.js
  src/architecture/repositories/login.repository.js
  src/architecture/services/login.service.js
  src/middlewares/authUser.middleware.js
  src/middlewares/login.middleware.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/passport/localStrategy.js
  src/routes/index.js
  src/routes/login.route.js
  src/util/token.js
Labels: backend, feature

#23 ✨ feat : authUser 파일에 refresh token 검증 추가
  src/middlewares/authUser.middleware.js
Labels: backend, feature

#24 ✨ FEAT : 기능 구현 및 에러 수정
  .vscode/settings.json
  package-lock.json
  package.json
  src/app.js
  src/architecture/controllers/login.controller.js
  src/architecture/controllers/products.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/login.repository.js
  src/architecture/repositories/products.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/index.js
  src/architecture/services/login.service.js
  src/architecture/services/products.service.js
  src/architecture/services/users.service.js
  src/middlewares/authUser.middleware.js
  src/middlewares/login.middleware.js
  src/migrations/20230102072551-create-users.js
  src/migrations/20230102072629-create-medicines.js
  src/migrations/20230102072644-create-saved-medicines.js
  src/models/medicines.js
  src/models/savedmedicines.js
  src/models/users.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/passport/localStrategy.js
  src/routes/index.js
  src/routes/login.route.js
  src/routes/products.route.js
  src/routes/users.route.js
  src/util/compare.js
  src/util/presignedUrl.js
  src/util/token.js
Labels: backend, feature

#41 :sparkles: #36 FEAT: 검색 기능 1차 구현
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/migrations/20230102072629-create-medicines.js
  src/models/medicines.js
  src/routes/products.route.js
Labels: backend

#42 ✨ #36 FEAT: 검색 기능 1차 구현
  package-lock.json
  src/architecture/controllers/products.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/products.service.js
  src/architecture/services/users.service.js
  src/migrations/20230102072551-create-users.js
  src/migrations/20230102072629-create-medicines.js
  src/models/medicines.js
  src/models/users.js
  src/routes/products.route.js
Labels: backend

#45 #40 ✨ feat : 유저 조회 구현
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/login.repository.js
  src/architecture/services/login.service.js
  src/architecture/services/users.service.js
  src/migrations/20230102072551-create-users.js
  src/models/users.js
  src/routes/users.route.js
  src/util/formatDate.js
Labels: backend

#48 #47 ✨ feat : 글귀 랜덤 조회 구현
  src/architecture/controllers/posts.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/posts.repository.js
  src/architecture/services/posts.service.js
  src/migrations/20230110113641-create-posts.js
  src/models/posts.js
  src/routes/index.js
  src/routes/post.route.js
Labels: backend, feature

#46 Merge pull request #45 from E-GaeMuYac/dev
  src/architecture/controllers/posts.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/login.repository.js
  src/architecture/repositories/posts.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/login.service.js
  src/architecture/services/posts.service.js
  src/architecture/services/users.service.js
  src/migrations/20230102072551-create-users.js
  src/migrations/20230110113641-create-posts.js
  src/models/posts.js
  src/models/users.js
  src/routes/index.js
  src/routes/post.route.js
  src/routes/users.route.js
  src/util/formatDate.js
Labels: backend

#52 🎨 #50 FEAT: 성분 테이블 분리 및 중간 테이블 생성
  src/migrations/20230102072629-create-medicines.js
  src/migrations/20230110052717-create-material.js
  src/migrations/20230110164714-create-ingredient.js
  src/models/ingredients.js
  src/models/materials.js
  src/models/medicines.js
Labels: backend, feature

#53 🎨 #50 FEAT: 성분 테이블 분리 및 중간 테이블 생성
  src/migrations/20230102072629-create-medicines.js
  src/migrations/20230110052717-create-material.js
  src/migrations/20230110164714-create-ingredient.js
  src/models/ingredients.js
  src/models/materials.js
  src/models/medicines.js
Labels: backend, feature

#56 #55 🎨 feat : 유저 정보 변경 분리
  src/architecture/controllers/users.controller.js
  src/architecture/services/users.service.js
  src/routes/users.route.js
Labels: backend

#58 ⚡ #51 FIX: 성분 기능 개선
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/migrations/20230110164716-create-ingredient.js
  src/models/ingredients.js
  src/models/materials.js
  src/models/medicines.js
Labels: backend, feature

#60 :zap: #51 FEAT: 성분 설명 업로드 api 추가
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/routes/products.route.js
Labels: backend, feature

#62 :sparkles: #54 FEAT: CRON 라이브러리를 이용한 스케줄링
  package-lock.json
  package.json
  src/util/autoupdate.js
Labels: backend, feature

#61 ✨ #51 FEAT: 구글 소셜 로그인 및 성분 기능 완료
  .aws/task-definition.json
  package-lock.json
  package.json
  src/app.js
  src/architecture/controllers/login.controller.js
  src/architecture/controllers/products.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/login.service.js
  src/architecture/services/users.service.js
  src/middlewares/authUser.middleware.js
  src/migrations/20230102072551-create-users.js
  src/migrations/20230110164716-create-ingredient.js
  src/models/ingredients.js
  src/models/materials.js
  src/models/medicines.js
  src/models/users.js
  src/passport/GoogleStrategy.js
  src/passport/NaverStrategy.js
  src/passport/index.js
  src/passport/localStrategy.js
  src/routes/login.route.js
  src/routes/products.route.js
  src/routes/users.route.js
  src/util/autoupdate.js
  src/util/token.js
Labels: backend, feature

#66 :zap: FIX: 자동 업로드파트 불필요한 코드 정리
  src/app.js
  src/util/autoupdate.js
Labels: documentation, backend

#68 ⚡ #36 FIX: 검색 기능 디테일 추가
  src/app.js
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/routes/products.route.js
Labels: documentation, backend, feature

#67 🎨 #57 FIX : passport 코드수정 및 네이버 로그인 추가
  package-lock.json
  package.json
  src/architecture/controllers/login.controller.js
  src/architecture/repositories/login.repository.js
  src/config/config.js
  src/middlewares/login.middleware.js
  src/migrations/20230102072551-create-users.js
  src/models/users.js
  src/passport/GoogleStrategy.js
  src/passport/NaverStrategy.js
  src/passport/index.js
  src/routes/login.route.js
  src/util/token.js
Labels: bug, backend

#72 #71 ✨ feat : 구글,네이버로그인카운트 추가
  src/architecture/repositories/login.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/login.service.js
  src/passport/GoogleStrategy.js
  src/passport/NaverStrategy.js
Labels: backend, feature

#70 :zap: #36 FIX: 코드 수정
  src/architecture/repositories/products.repository.js
Labels: bug, backend, feature

#74 🎨 FIX : 버그 수정
  src/passport/NaverStrategy.js
Labels: bug, backend

#69 ⚡ FIX: 검색 기능 디테일 추가 및 소셜 로그인, 로그인 카운트 구현
  package-lock.json
  package.json
  src/architecture/controllers/login.controller.js
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/login.repository.js
  src/architecture/repositories/products.repository.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/login.service.js
  src/architecture/services/products.service.js
  src/config/config.js
  src/middlewares/login.middleware.js
  src/migrations/20230102072551-create-users.js
  src/models/users.js
  src/passport/GoogleStrategy.js
  src/passport/NaverStrategy.js
  src/passport/index.js
  src/routes/login.route.js
  src/routes/products.route.js
  src/util/autoupdate.js
  src/util/token.js
Labels: documentation, backend, feature

#75 ✨ #65 FEAT : 카카오 소셜 로그인 기능 구현
  src/architecture/controllers/login.controller.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/routes/login.route.js
Labels: bug, backend

#76 #71 ✨ feat : 카카오 로그인 카운트 구현
  .aws/task-definition.json
  src/passport/kakaoStrategy.js
Labels: backend, feature

#79 #78 🐛 fix : 정규표현식 수정
  src/architecture/controllers/users.controller.js
Labels: bug, backend

#87 🐛 FIX : Cors에러 해결
  README.md
  src/app.js
  src/architecture/controllers/login.controller.js
  src/passport/KakaoStrategy.js
Labels: bug, backend

#91 #90 🐛 fix : 패스워드 벨리데이션 수정
  src/architecture/controllers/login.controller.js
  src/architecture/controllers/users.controller.js
Labels: bug, backend

#95 Merge pull request #95 from E-GaeMuYac/dev
  src/app.js
  src/architecture/controllers/login.controller.js
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/login.service.js
  src/architecture/services/users.service.js
Labels: backend

#99 :sparkles: FIX : res.header에서 res.redirect로 변경
  src/architecture/controllers/login.controller.js
Labels: bug, backend

#97 #96✨ feat : 이메일로 휴대폰번호 찾기 구현
  src/architecture/controllers/users.controller.js
  src/architecture/services/users.service.js
  src/routes/users.route.js
Labels: backend, feature

#104 #98 ✨ feat : 회원가입 시 기본이미지 설정
  src/architecture/repositories/users.repository.js
  src/architecture/services/users.service.js
  src/migrations/20230102072551-create-users.js
  src/models/users.js
  src/passport/GoogleStrategy.js
  src/passport/KakaoStrategy.js
  src/passport/NaverStrategy.js
Labels: backend, feature

#108 ⚡ #106 FIX : 검색 기능 디테일 추가
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/middlewares/authCheck.middleware.js
  src/routes/products.route.js
Labels: enhancement, backend

#113 #112 🎨 feat : 회원탈퇴 소셜로그인 수정
  src/architecture/services/users.service.js
  src/middlewares/authUser.middleware.js
Labels: backend

#110 ⚡ #106 #107 FIX : 검색, 상세보기, 비교하기 페이지 디테일 수정
  src/architecture/controllers/login.controller.js
  src/architecture/controllers/products.controller.js
  src/architecture/repositories/products.repository.js
  src/architecture/services/products.service.js
  src/architecture/services/users.service.js
  src/middlewares/authCheck.middleware.js
  src/middlewares/authUser.middleware.js
  src/routes/products.route.js
Labels: enhancement, backend

#114 :zap: #106 #107 FIX : 약품 타입 개선 요청
  src/architecture/services/products.service.js
Labels: enhancement, backend

#115 :zap: #106 #107 FIX : 약품 타입 개선 요청 dev to main
  src/architecture/services/products.service.js
Labels: enhancement, backend

#117 :art: FIX : 잘못된 코드 수정
  src/architecture/controllers/login.controller.js
Labels: invalid, backend

#118 :art: FIX : 잘못된 코드 수정
  src/architecture/controllers/login.controller.js
Labels: backend

#120 #119 🐛 fix : 로그아웃 토큰 값 변경
  src/architecture/repositories/users.repository.js
Labels: bug, backend

#123 🎨 Fix : detail
  src/architecture/services/products.service.js
  src/middlewares/authCheck.middleware.js
  src/util/autoupdate.js
Labels: enhancement, backend

#125 #122 🎨 fix : 이메일 유니크값 false 및 Local만 중복 불가로 구현
  src/architecture/services/users.service.js
  src/migrations/20230102072552-create-users.js
  src/migrations/20230102072645-create-saved-medicines.js
  src/models/users.js
Labels: bug, backend

#126 🔥 # 122 FIX : 불필요한 코드 삭제
  package.json
  src/architecture/services/products.service.js
  src/architecture/services/users.service.js
  src/middlewares/authCheck.middleware.js
  src/migrations/20230102072552-create-users.js
  src/migrations/20230102072645-create-saved-medicines.js
  src/models/users.js
  src/passport/GoogleStrategy.js
  src/passport/KakaoStrategy.js
  src/passport/NaverStrategy.js
  src/util/autoupdate.js
Labels: backend

#129 #127 🐛 fix : 한글 인코딩문제 해결
  src/architecture/services/users.service.js
  src/passport/GoogleStrategy.js
  src/passport/KakaoStrategy.js
  src/passport/NaverStrategy.js
Labels: bug, backend

#132 #127 🐛 fix : 파일네임 인코딩 및 쿼리로 수정
  src/architecture/controllers/users.controller.js
  src/architecture/services/users.service.js
Labels: bug, backend

#134 :art: FIX : 사용하지 않는 라이브러리 정리
  package.json
Labels: backend, feature

#136 :art: #135 FIX : 검색 기능 수정
  src/architecture/services/products.service.js
Labels: bug, backend

#143 🚑 FIX : Strategies 파일에 else문 추가
  package-lock.json
  package.json
  src/passport/GoogleStrategy.js
  src/passport/KakaoStrategy.js
  src/passport/NaverStrategy.js
  src/swagger.js
Labels: bug, backend

#145 #144 🔥 fire : 코드 정리
  README.md
  src/config/config.js
Labels: backend

#152 🗃️ #147 DOCS : Models와 Migrations 생성
  package-lock.json
  src/architecture/controllers/review.controller.js
  src/architecture/repositories/review.repository.js
  src/architecture/services/review.service.js
  src/migrations/20230112072646-create-reivews.js
  src/models/medicines.js
  src/models/reviews.js
  src/models/users.js
  src/routes/index.js
Labels: bug, backend

#155 :ambulance: # 147 FIX : 실수코드 수정
  src/models/users.js
Labels: bug, backend

#165 #164 🎨 feat : 유저 정보 조회 시 유저아이디 추가
  src/architecture/services/users.service.js
Labels: backend

#168 #166 🐛 fix : 이메일 중복 검사 추가
  src/architecture/services/users.service.js
Labels: bug, backend

#174 :truck: #173 FIX : 소셜 로그인 redirect url 수정
  src/architecture/controllers/login.controller.js
  src/architecture/services/reviews.service.js
Labels: bug, backend

#176 #175 🎨 fix : 코드 구조 개선
  src/architecture/controllers/reviews.controller.js
  src/architecture/services/reviews.service.js
  src/middlewares/authCheck.middleware.js
  src/migrations/20230112072646-create-reivews.js
Labels: documentation, backend

#179 :sparkles: #178 FEAT : like/dislike 기능 구현
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/routes/reviews.route.js
Labels: backend, feature

#180 배포
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/routes/reviews.route.js
Labels: backend

#182 :bug: #159 FIX : 에러 코드 수정
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/migrations/20230122112551-create-dislikes.js
  src/models/index.js
  src/routes/login.route.js
  src/routes/reviews.route.js
Labels: bug, backend

#183 merge from dev to main
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/migrations/20230122112551-create-dislikes.js
  src/models/index.js
  src/routes/login.route.js
  src/routes/reviews.route.js
Labels: backend

#185 ✨ #184 FEAT : 리뷰 기능 추가
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
  src/migrations/20230112072645-create-reivews.js
  src/migrations/20230112072646-create-reviews.js
  src/migrations/20230122112549-create-likes.js
  src/migrations/20230122112552-create-dislikes.js
  src/migrations/20230122112552-create-likes.js
  src/migrations/20230122112554-create-dislikes.js
Labels: enhancement, backend, feature

#188 #187 ✨ feat : 이메일, 휴대폰 인증 요청 추가
  .aws/task-definition.json
  .prettierignore
  .prettierrc.json
  src/architecture/controllers/users.controller.js
  src/architecture/services/users.service.js
  src/routes/users.route.js
  src/util/token.js
Labels: backend, feature

#190 :zap: #189 FIX : 리뷰 조회시 유저의 imageUrl 추가
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: enhancement, backend

#192 merge from dev to main
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: backend

#194 :zap: #193 FIX : 리뷰 조회시 도움돼요 순으로 정렬 추가
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: enhancement, backend, feature

#195 merge from dev to main
  src/architecture/controllers/reviews.controller.js
  src/architecture/repositories/reviews.repository.js
  src/architecture/services/reviews.service.js
Labels: backend

#197 #196 ✨ feat : Rate Limit 미들웨어 구현 및 적용
  package-lock.json
  package.json
  src/middlewares/login.middleware.js
  src/middlewares/rateLimit.middleware.js
  src/routes/users.route.js
Labels: backend, feature

#199 #198 🐛 fix : 이메일 찾기 수정
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/users.service.js
  src/routes/users.route.js
Labels: backend

#202 #201 🚑 feat : 이메일 찾기 롤백 및 휴대폰 중복검사 추가
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/users.service.js
  src/routes/users.route.js
Labels: backend

#205 #204 🚑 fix : Rate Limit 미들웨어 에러 수정
  src/architecture/controllers/users.controller.js
  src/architecture/repositories/users.repository.js
  src/architecture/services/users.service.js
  src/middlewares/rateLimit.middleware.js
  src/routes/users.route.js
Labels: bug, backend
